### ISSUE TITLE
docker labels sample

### ISSUE THREAD

**Issue by heroes1412** [Paxxs/traefik-get-real-ip#7]
im using docker swarm cluster, and dont know how to parse label to use this plugin, anybody help?

**Comment by xanderificnl** [comment]
Maybe my comment here will help: https://github.com/Paxxs/traefik-get-real-ip/issues/6#issuecomment-1258484638

**Comment by heroes1412** [comment]
it was just a swarm lab, i had moved to k8s cluster lab already, thank for your help, maybe it will help other people :D
